# Use Node.js base image
FROM node:18

# Set working directory
WORKDIR /usr/src/smartcontractapi

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Copy the connection-org1.json file specifically
COPY ../test-network/organizations/peerOrganizations/org1.example.com/connection-org1.json ./test-network/organizations/peerOrganizations/org1.example.com/

# Expose the port
EXPOSE 3000

# Command to run the app
CMD ["node", "dist/smartcontractapi.js"]
