FROM node:18
WORKDIR /usr/src/smartcontractapi
COPY package*.json ./
RUN npm install
COPY . .
COPY ../test-network/organizations/peerOrganizations/org1.example.com/connection-org1.json ./test-network/organizations/peerOrganizations/org1.example.com/
EXPOSE 3000
CMD ["node", "dist/smartcontractapi.js"]
